[art-type.3d-rendering]
    StyleName = "3d-rendering"
    Positive = 'Professional 3D rendering,CGSociety,ArtStation'
    Negative = '((Wireframe)),Polygons,Screenshot,Character design,Software,UI'
[art-type.digital-artwork]
    StyleName = "digital-artwork"
    Positive = 'Digital Artwork,CGSociety,ArtStation'
    Negative = 'Scribbles,Low quality,Low rated,Mediocre,3D rendering,Screenshot,Software,UI'
[art-type.drawing]
    StyleName = "drawing"
    Positive = 'Drawing'
    Negative = 'Low quality,Photo,Artifacts,Table,Paper,Pencils,Pages,Wall'
[art-type.painting]
    StyleName = "painting"
    Positive = 'Painting'
    Negative = 'Low quality,Bad composition,Faded,(Photo:1.5),(Frame:1.3)'
[art-type.photo]
    StyleName = "photo"
    Positive = 'Photo, Highly Detailed'
    Negative = 'Low rated,Phone,Wedding,Frame,Painting,tumblr'
[art-type.vector-art]
    StyleName = "vector-art"
    Positive = 'Vector art'
    Negative = '(Watermark:1.5),(Text:1.3)'
[concepts]
concepts = [
    "Acclaimed",
    "Alternative",
    "Amateur",
    "Artificial",
    "Award Winning",
    "Basic",
    "Beginner",
    "Bipolar",
    "Boyish",
    "Childish",
    "Cinematic",
    "Clever",
    "Clumsy",
    "Cognitive",
    "Complex",
    "Compressed",
    "Controllable",
    "Corrupted",
    "Damaged",
    "Destroyed",
    "Disgusting",
    "Divisive",
    "Dramatic",
    "Dumb",
    "Eliminated",
    "Excessive",
    "Exciting",
    "Extreme",
    "Feminine",
    "Filtered",
    "Fixated",
    "Fixed",
    "Foolish",
    "Fragile",
    "Girlish",
    "Gorgeous",
    "Groundbreaking",
    "Hated",
    "Hidden",
    "Highly Rated",
    "Horrifying",
    "Imaginary",
    "Imaginative",
    "Imitated",
    "Jaded",
    "Light hearted",
    "Loved",
    "Low Rated",
    "Magical",
    "Masculine",
    "Masterful",
    "Masterpiece",
    "Maximalist",
    "Methodological",
    "Misunderstood",
    "Mundane",
    "Overprocessed",
    "Pathetic",
    "Photoshopped",
    "Preview",
    "Raw",
    "Recycled",
    "Religious",
    "Rough",
    "Sacrificial",
    "Sacrilegious",
    "Schematic",
    "Simple",
    "Sophisticated",
    "Stupid",
    "Trustworthy",
    "Unbelievable",
    "Understandable",
    "Unearthed",
    "Unfiltered",
    "Unfinished",
    "Unhinged",
    "Universal",
    "Unsuccessful",
    "Venerable",
    "Visionary",
    "Vivacious"
]
[artists]
artists = [
    "Adam Hughes",
    "Adi Granov",
    "Adolf Kosarek",
    "Adolph Von Menzel",
    "Akihiko Yoshida",
    "Al Williamson",
    "Albert Lynch",
    "Alberto Seveso",
    "Alberto Vargas",
    "Alena Aenami",
    "Alex Andreev",
    "Alex Grey",
    "Alex Ross",
    "Alex Toth",
    "Alexander Archipenko",
    "Alexander Jansson",
    "Alfred Steiglitz",
    "Alphonse Mucha",
    "Alvar Aalto",
    "Anato Finnstark",
    "Andre Masson",
    "Andrew Loomis",
    "Andy Fairhurst",
    "Anna Dittman",
    "Apollonia Saintclair",
    "Artgerm",
    "Arthur Adams",
    "Arthur Rackham",
    "Aubrey Beardsley",
    "Austin Briggs",
    "Ayami Kojima",
    "Barbara Kruger",
    "Bastien Lecouffe Deharme",
    "Beeple",
    "Bill Sienkiewicz",
    "Bill Ward",
    "Bo Bartlett",
    "Bob Byerley",
    "Bob Eggleton",
    "Bob Haberfield",
    "Bob Peak",
    "Boris Vallejo",
    "Brandon Woelfel",
    "Brian Bolland",
    "Brian Froud",
    "Bruce Pennington",
    "Bryan Hitch",
    "Butcher Billy",
    "Camille Walala",
    "Carel Willink",
    "Carmine Infantino",
    "Carrie Ann Baade",
    "Casey Baugh",
    "Casey Weldon",
    "Cedric Peyravernay",
    "Charles Adams",
    "Charlie Bowater",
    "Chesley Bonestell",
    "Chris Foss",
    "Christopher Balaskas",
    "Claude Monet",
    "Clive Barker",
    "Coles Phillips",
    "Conrad Roset",
    "Curt Swan",
    "Dan Mumford",
    "Diego Rivera",
    "Don Bergland",
    "Donato Giancola",
    "Dorina Costras",
    "E.H. Shepard",
    "Earl Norem",
    "Earle Bergey",
    "Earnst Haeckel",
    "Ed Emshwiller",
    "Ed Mell",
    "Edith Head",
    "Edmund Dulac",
    "Edvard Munch",
    "Ellen Jewett",
    "Emily Balivet",
    "Enki Bilal",
    "Eric Kennington",
    "Erin Hanson",
    "Ernie Barnes",
    "Esao Andrews",
    "Esteban Maroto",
    "Ethan Van Sciver",
    "Eve Ventrue",
    "Eyvind Earle",
    "F. Scott Hess",
    "Fernand Khnopff",
    "Filippino Lippi",
    "Frank Bowling",
    "Frank Cadogan Cowper",
    "Frank Frazetta",
    "Frank Tenney Johnson",
    "Frank Xavier",
    "Franklin Booth",
    "Fred Calleri",
    "Fujishima Takeji",
    "Gabriel Von Max",
    "Gediminas Pranckevicius",
    "Gene Colan",
    "Geof Darrow",
    "Georgia O’Keeffe",
    "Georgy Kurasov",
    "Gerald Brom",
    "Gertrude Abercrombie",
    "Gil Elvgren",
    "Gil Kane",
    "Greg Manchess",
    "Greg Rutkowski",
    "Gustaf Tenggren",
    "Gustav Klimt",
    "H.P. Lovecraft",
    "H.R. Giger",
    "Hannah Yata",
    "Harrison Fisher",
    "Harry Clarke",
    "Henri Matisse",
    "Henry Clive",
    "Herbert James Gunn",
    "Hikari Shimoda",
    "Hiroshi Nagai",
    "Hiroshi Yoshida",
    "Hsiao-Ron Cheng",
    "Huang Guangjian",
    "Ian Kennedy",
    "Igor Morski",
    "Igor Zenin",
    "Ilya Kuvshinov",
    "Ilya Repin",
    "Ivan Aivazovsky",
    "Ivan Bilibin",
    "J.C. Leyendecker",
    "Jacek Yerka",
    "Jack Kirby",
    "Jackson Pollock",
    "James C. Christensen",
    "James Gilleard",
    "James Gurney",
    "James Jean",
    "Jan Hendrik Weissenbruch",
    "Jan Urschel",
    "Jasmine Becket-Griffith",
    "Jason Edmiston",
    "Jay Anacleto",
    "Jean Giraud",
    "Jeannette Guichard-Bunel",
    "Jeffrey Smith",
    "Jeremiah Ketner",
    "Jeremy Lipking",
    "Jian Chong Min",
    "Jim Burns",
    "Jim Holland",
    "Joao Ruas",
    "Joe Jusko",
    "Joe Kubert",
    "Johan Heinrich Fussli",
    "John Howe",
    "John Lavery",
    "John Philip Falter",
    "John Romita Jr",
    "John Singer Sargent",
    "John T. Biggers",
    "Jon Whitcomb",
    "Joop Polder",
    "Joseph Leyendecker",
    "Juan Gris",
    "Julian Onderdonk",
    "Junji Ito",
    "Kadir Nelson",
    "Karel Thole",
    "Karol Bak",
    "Kawase Hasui",
    "Kaws",
    "Kehinde Wiley",
    "Kelly McKernan",
    "Koho Shoda",
    "Krenz Cushart",
    "Lee Bogle",
    "Leonardo Coccorante",
    "Leonid Afremov",
    "Lisa Frank",
    "Loish",
    "Lyubov Popova",
    "M.C. Escher",
    "Makoto Shinkai",
    "Marc Chagall",
    "Marc Simonetti",
    "Mark Ryden",
    "Martin Ansin",
    "Martin Schongauer",
    "Mary Jane Ansell",
    "Masamune Shirow",
    "Mati Klarwein",
    "Maxfield Parrish",
    "Mead Schaeffer",
    "Michael Cheval",
    "Michael Whelan",
    "Miho Hirano",
    "Mike Allred",
    "Mike Mignola",
    "Mike Winkelmann",
    "Miles Aldridge",
    "Milton Caniff",
    "Moebius",
    "Mort Kunstler",
    "Neal Adams",
    "Nikolai Astrup",
    "Njideka Akunyili Crosby",
    "Norman Rockwell",
    "P.A. Works",
    "Pang Xunqin",
    "Paul Cadmus",
    "Paul Lehr",
    "Paul Signac",
    "Peter Elson",
    "Peter Gric",
    "Peter Mohrbacher",
    "Peter Wileman",
    "Petros Afshar",
    "Phil Noto",
    "Philippe Druillet",
    "Rafael Albuquerque",
    "Ralph Gibson",
    "Raymond Swanland",
    "RHADS",
    "Richard Avedon",
    "Richard Corben",
    "Richard Lindner",
    "Rob Gonsalves",
    "Robert Bissell",
    "Robert McCall",
    "Roberto Matta",
    "Rolf Armstrong",
    "Romero Britto",
    "Ron Miller",
    "Ross Tran",
    "RossDraws",
    "Roy Lichtenstein",
    "Ruan Jia",
    "Ryan Pancoast",
    "Ryohei Hase",
    "Sabbas Apterus",
    "Sachin Teng",
    "Salvador Dali",
    "Sam bosma",
    "Sam Gilliam",
    "Scott Listfield",
    "Shigenori Soejima",
    "Shinji Aramaki",
    "Simon Bisley",
    "Simon Stalenhag",
    "Siya Oum",
    "Stanhope Forbes",
    "Stanislaw Wyspianski",
    "Stephan Martinière",
    "Steve Ditko",
    "Syd Mead",
    "Takashi Murakami",
    "Tara McPherson",
    "Tarsila do Amaral",
    "Ted Nasmith",
    "Theo Van Rysselberghe",
    "Thomas Blackshear",
    "Thomas Kinkade",
    "Thomas Shotter Boys",
    "Todd McFarlane",
    "Tom Bagshaw",
    "Tom Lovell",
    "Tom Whalen",
    "Tomer Hanuka",
    "Trevor Brown",
    "Trina Robbins",
    "Tsutomu Nihei",
    "Ulisse Aldrovandi",
    "Umberto Boccioni",
    "Vasily Vereschagin",
    "Victo Ngai",
    "Victor Nizovtsev",
    "Vincent DiFate",
    "Vittorio Reggianini",
    "W. Heath Robinson",
    "Wadim Kashin",
    "Walter Crane",
    "Wangechi Mutu",
    "Warwick Goble",
    "Wayne Barlowe",
    "Will Barnet",
    "William Dodge",
    "William Eggleston",
    "William Holbrook Beard",
    "William McGregor Paxton",
    "WLOP",
    "Yanjun Cheng",
    "Yoji Shinkawa",
    "Yoshitaka Amano",
    "Zdzislaw Beksinski"
]
[art-movements]
art-movements = [
    "50s Art",
    "60s Art",
    "70s Art",
    "80s Art",
    "Abstract Art",
    "Abstract Expressionism",
    "Abstract Illusionism",
    "Academism",
    "Action Painting",
    "Aestheticism",
    "Afrofuturism",
    "American Impressionism",
    "American Scene Painting",
    "Art Brut",
    "Art Deco",
    "Art Nouveau",
    "Art Photography",
    "Arts and Crafts Movement",
    "Ascii Art",
    "Ashcan School",
    "Australian Tonalism",
    "Baroque Art",
    "Bauhaus Art",
    "Berlin Secession",
    "CGI Art",
    "Classical Realism",
    "Classicism Art",
    "Cloisonnism",
    "Computer Art",
    "Conceptual Art",
    "Constructivism Art",
    "Crystal Cubism",
    "Cubism",
    "Cubo-Futurism",
    "Cutester Art",
    "Cybergoth Art",
    "Cyberpunk Art",
    "Dada Art",
    "Dark Wave Art",
    "Digital Art",
    "Emo Art",
    "Expressionism",
    "Fauvism",
    "Figurative Art",
    "Fluxus Art",
    "Folk Art",
    "Funk Art",
    "Futurism",
    "Geometric Abstract Art",
    "Glitch Art",
    "Graffiti Street Art",
    "Grunge Art",
    "Gutai Group",
    "Hardcore Art",
    "Harlem Renaissance",
    "Health Goth Art",
    "Heidelberg School",
    "Hippie Art",
    "Hipster Art",
    "Hyperrealism",
    "Impressionism",
    "Industrial Art",
    "Kinetic Pointillism",
    "Land Art",
    "Lowbrow Art",
    "Lyrical Abstraction",
    "Magical Realism",
    "Mannerism Art",
    "Memecore Art",
    "Metaphysical Painting",
    "Mingei",
    "Minimalism Art",
    "Modern Art",
    "Modern European Ink Painting",
    "Modernism Art",
    "Naive Art",
    "Neo Dada Art",
    "Neo",
    "Neo-Dadaism Art",
    "Neo-Expressionism",
    "Neo-Fauvism",
    "Neo-Primitivism",
    "Neoclassicism",
    "Neogothic Art",
    "New Wave Art",
    "Normcore Art",
    "Nu Goth Art",
    "Orphism",
    "Panfuturism",
    "Pastel Goth Art",
    "Photorealism",
    "Pixel Art",
    "Pointillism",
    "Pop Art",
    "Post-Impressionism",
    "Pre-Raphaelitism",
    "Primitivism Art",
    "Primitivism",
    "Private Press",
    "Process Art",
    "Psychedelic Art",
    "Psytrance Art",
    "Qajar Art",
    "Queercore Art",
    "Realism",
    "Remodernism",
    "Renaissance",
    "Retrofuturism",
    "Rococo",
    "Seapunk Art",
    "Serial Art",
    "Shin Hanga",
    "Solarpunk Art",
    "Steampunk Art",
    "Street Art",
    "Suprematism",
    "Surrealism Art",
    "Synthetism",
    "Sōsaku Hanga",
    "Temp",
    "Tonalism",
    "Toyism Art",
    "Ukiyo-E",
    "Vanitas",
    "Vaporwave Art",
    "Victorian Gothic Art",
    "Vorticism Art",
    "Yuccie Art"
]
[colors]
colors=[
    "Agfacolor",
    "Blue hue",
    "BW",
    "Cathode tube",
    "CineColor",
    "CMYK Colors",
    "Cold Colors",
    "Colorful",
    "Colorless",
    "Cyan hue",
    "Dark hue",
    "Desaturated",
    "Dichromatic",
    "Electric Colors",
    "Fujifilm Superia",
    "Grayscale",
    "Green hue",
    "High Contrast",
    "Hypersaturated",
    "Infrared",
    "Kinemacolor",
    "Kodachrome",
    "Kodak Ektar",
    "Kodak Portra",
    "Low Contrast",
    "Magenta hue",
    "Mono Color",
    "Muted Colors",
    "Offset print",
    "One Color",
    "Oversaturated",
    "Pastel Colors",
    "Polychromatic",
    "Primary Colors",
    "Provia",
    "Purple hue",
    "Red hue",
    "Saturated",
    "Single Color",
    "Technicolor",
    "Velvia",
    "Vivid Colors",
    "Warm Colors",
    "Yellow hue"
]
[directions]
directions=[
    "Cel shaded",
    "Cel shading",
    "Detailed illustration",
    "Graphic novel",
    "Illustration",
    "Masterpiece",
    "Realistic",
    "Rough sketch",
    "Screen print",
    "Simple illustration",
    "Sketch",
    "Sketched",
    "Technical illustration",
    "Ultra detailed",
    "Ultrarealistic",
    "Visual novel"
]
[moods]
moods=[
    "Amusing",
    "Angry",
    "Cosy",
    "Depressing",
    "Disgusting",
    "Embarrassing",
    "Energetic",
    "Evil",
    "Fearful",
    "Frightening",
    "Grim",
    "Guilty",
    "Happy",
    "Hopeful",
    "Hopeless",
    "Lonely",
    "Lustful",
    "Peaceful",
    "Proud",
    "Relieving",
    "Romantic",
    "Sad",
    "Satisfying",
    "Shameful",
    "Surprising"
]